# Generated by Django 3.0.7 on 2020-06-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrents',
            name='download_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=15),
        ),
        migrations.AddField(
            model_name='torrents',
            name='downloaded_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torrents',
            name='file_hash',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='torrents',
            name='number_of_peers_connected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torrents',
            name='number_of_seeders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torrents',
            name='total_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrents',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
