# Generated by Django 3.0.7 on 2020-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourint', '0002_auto_20200622_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrents',
            name='download_directory',
            field=models.CharField(default='./downloads/', max_length=255),
        ),
    ]
